[build]
builder = "NIXPACKS"

[deploy]
startCommand = "npm run preview -- --host 0.0.0.0"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"

[env]
NODE_ENV = "production"