services:
  # Full-stack application (React frontend + Express backend)
  - type: web
    name: inmobiliaria-fullstack
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    rootDir: ./
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      # ADMIN_USERNAME and ADMIN_PASSWORD should be set manually in Render dashboard
      # for security - do not commit credentials to git