services:
  - type: web
    name: inmobiliaria-backend
    env: node
    plan: starter
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        sync: false
      - key: JWT_SECRET  
        generateValue: true
      - key: ADMIN_USERNAME
        value: admin  
      - key: ADMIN_PASSWORD
        value: inmobiliaria2024